class AppConstants {
  AppConstants._();

  static String supaBaseAnonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96b2pza29pY216dWtmanJncXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzcxNjcsImV4cCI6MjA2NTcxMzE2N30.y1KFgPRr3VNG30L5QX5UwrWqmvV2SR6kxi59_fkwSss';
  static String supaBaseProjectKey = 'https://ozojskoicmzukfjrgqvs.supabase.co';
  static List<String> airlineNames = [
    "Aegean Airlines",
    "Aer Lingus",
    "Aeroflot",
    "Aerolineas Argentinas",
    "Aeromas",
    "Aeromexico",
    "Aero Ejecutivos",
    "Air Arabia",
    "Air Astana",
    "Air Austral",
    "Air Baltic",
    "Air Belgium",
    "Air Berlin",
    "Air Canada",
    "Air Caraibes",
    "Air China",
    "Air Class",
    "Air Corsica",
    "Air Deccan",
    "Air Dolomiti",
    "Air Europa",
    "Air France",
    "Air India",
    "Air India Express",
    "Air Macau",
    "Air Malta",
    "Air Mauritius",
    "Air Namibia",
    "Air New Zealand",
    "Air North",
    "Air Sahara",
    "Air Seoul",
    "Air Serbia",
    "Air Tahiti",
    "Air Tahiti Nui",
    "Air Transat",
    "Air Vanuatu",
    "AirAsia",
    "AirAsia X",
    "Aircalin",
    "Alaska Airlines",
    "Alitalia",
    "Allegiant",
    "All Nippon Airways",
    "Alliance Air",
    "America West",
    "American Airlines",
    "Asiana",
    "Austrian",
    "Avior Airlines",
    "Azerbaijan Hava Yollary",
    "Azores Airlines",
    "Azul",
    "BA Cityflyer",
    "BA Euroflyer",
    "Bamboo Airways",
    "Blue Wing Airlines",
    "British Airways",
    "British Caledonian",
    "Cathay Pacific",
    "Continental",
    "Conviasa",
    "Damania Airways",
    "Delta",
    "Dragon Air",
    "East West Airways",
    "Eastern",
    "Emirates",
    "Etihad Airways",
    "Eva Air",
    "Frontier Airlines",
    "GoAir",
    "Hinterland Aviation",
    "Indian Airlines",
    "IndiGo",
    "InterJet",
    "Jags Aviation",
    "Japan Airlines",
    "Jet Airways",
    "Jet2.com",
    "JetBlue",
    "JetKonnect",
    "Jetstar",
    "Jetstar Asia",
    "Kingfisher Airlines",
    "Korean Air",
    "LAI - Línea Aérea IAACA",
    "LATAM Paraguay",
    "LATAM Perú",
    "Laser Airlines",
    "Lauda Air",
    "Lufthansa",
    "Malta Air",
    "Movil Air",
    "My Airline",
    "NEPC Airlines",
    "Northwest",
    "Oxford Aviation",
    "Pan Am",
    "Paranair",
    "Paramount Airways",
    "Pegasus Airlines",
    "Philippine Airlines",
    "Planet",
    "Qantas",
    "Qatar Airways",
    "Roraima Airways",
    "Rutaca",
    "Ryanair",
    "Ryanair UK",
    "SAETA Peru",
    "SABENA",
    "Saudia",
    "Silver",
    "Singapore Airlines",
    "Sol America",
    "Sol del Paraguay",
    "Southwest Airlines",
    "Spirit Airlines",
    "Star Peru",
    "Surinam Airways",
    "SwissAir",
    "TACA",
    "TED",
    "Thomas Cook",
    "Tigerair",
    "Trans Guyana Airways",
    "Turkish Airlines",
    "TWA",
    "United Airlines",
    "United Express",
    "US Airways",
    "USA3000",
    "Varig",
    "Vayudoot",
    "Venezolana",
    "Virgin America",
    "Virgin Atlantic",
    "Vistara",
    "Wizz Air",
    "Wizz Air Abu Dhabi",
    "Wizz Air Malta",
    "easyJet",
  ];
}
